<a href="https://colab.research.google.com/github/sohagalam2/Python-Code-Practice/blob/master/Exercises_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Documentation reading
*Reading Done*

##2. Create a random tensor with shape (7,7)

In [ ]:
#import Torch
import torch
random_tensor = torch.rand(7,7)
print(f"Random Tensor: \n{random_tensor}")

Random Tensor: 
tensor([[0.9148, 0.3414, 0.9796, 0.9872, 0.9393, 0.1978, 0.5210],
        [0.7114, 0.3394, 0.0658, 0.8746, 0.4421, 0.6170, 0.6080],
        [0.1505, 0.0215, 0.2201, 0.8649, 0.2248, 0.3089, 0.2655],
        [0.2258, 0.3944, 0.0563, 0.7742, 0.2642, 0.0159, 0.7420],
        [0.1153, 0.0538, 0.8568, 0.5485, 0.2226, 0.3875, 0.5383],
        [0.4803, 0.5862, 0.8828, 0.9504, 0.1797, 0.9071, 0.4248],
        [0.1978, 0.6762, 0.7994, 0.4013, 0.6732, 0.4570, 0.7628]])


3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1,7)

In [ ]:
random_tensor_one = random_tensor
random_tensor_two = torch.rand(1,7)

# print(f"Random tensor two: \n{torch.transpose(random_tensor_two)}")
print(f"Tensor multiplication: \n{torch.matmul(random_tensor_one, random_tensor_two.T)}")

Tensor multiplication: 
tensor([[3.5632],
        [2.7593],
        [1.4554],
        [1.9226],
        [2.1683],
        [3.5779],
        [3.0392]])


## Set the random seed to 0 and do 2 & 3 over again.

In [ ]:
#import torch
import torch
MANUAL_SEED = 0
torch.manual_seed(MANUAL_SEED)
random_tensor_one = torch.rand(7,7)
torch.manual_seed(MANUAL_SEED)
random_tensor_two = torch.rand(1,7)
#So, if we call twice, every time it will reset and thus result will be different
#as we found here and look the result below.
print(f"Tensor Multiplication: \n{torch.matmul(random_tensor_one, random_tensor_two.T)},size: \n{torch.matmul(random_tensor_one, random_tensor_two.T).size()}")



Tensor Multiplication: 
tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]),size: 
torch.Size([7, 1])


In [ ]:
#here same task, calling manual seed once.
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

##Speaking of random seeds, is there a GPU equivalent? if there is, set the GPU random seed to 1234



In [ ]:
#set the random manual on GPU
torch.manual_seed(1234)


##6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [ ]:
#random seed call
torch.manual_seed(1234)
#availability check
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
print(f"Device: \n{device}")

#create two random tensor on GPU
tensor_one = torch.rand(2,3).to(device)
tensor_two = torch.rand(2,3).to(device) #although same call, yet different random number generates
tensor_one, tensor_two

Device: 
cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

##7. Perform a matrix multiplication on the tensors you created in 6

In [ ]:
#perform matmul on tensor_one and tensor_two
result = torch.matmul(tensor_one, tensor_two.T)
print(f"Matrix multiplication: \n{result}")

Matrix multiplication: 
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


##8. Find the maximum and minimum values of the output of 7.

In [ ]:
#find max
print(f"max: {result.max()}")

#find min
print(f"min: {result.min()}")

max: 0.5617256760597229
min: 0.3647301495075226


##9. Find the maximum and minimum index values of the output of 7.

In [ ]:
#find arg max
print(f"arg max: {result.argmax()}")

#find arg min
print(f"arg min: {result.argmin()}")

arg max: 3
arg min: 0


##10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
#set the seed
torch.manual_seed(7)
#create random tensor
random_tensor = torch.rand(1,1,1,10)
print(f"Random tensor: \n{random_tensor}")
print(f"Random tensor shape: \n{random_tensor.shape}")
#remove the single dimensions
One_dimension_removed = random_tensor.squeeze()
print(f"Result: \n{One_dimension_removed}")
print(f"Result shape: \n{One_dimension_removed.shape}")

Random tensor: 
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Random tensor shape: 
torch.Size([1, 1, 1, 10])
Result: 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Result shape: 
torch.Size([10])
